# Generated by Django 5.0.4 on 2024-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.URLField(default="https://example.com", max_length=500),
            preserve_default=False,
        ),
    ]
