# Generated by Django 5.0.4 on 2024-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchapp", "0002_article_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
