# Generated by Django 4.2.13 on 2024-08-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_userprofile_questionresponse_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.userprofile'),
        ),
    ]
