# Generated by Django 4.2.13 on 2024-09-03 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='score.userprofile'),
        ),
    ]
