# Generated by Django 4.2.13 on 2024-09-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_usertype_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.userprofile'),
        ),
    ]
