# Generated by Django 4.2.13 on 2024-09-17 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0007_alter_usertype_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('matched_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
