# Generated by Django 4.2.13 on 2024-09-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-matched_on']},
        ),
    ]
